In [2]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator


In [5]:
df = pd.read_csv('train.csv')
df.columns =['Text','Emotion']

In [4]:
df.head()

i didnt feel humiliated  sadness
0  i can go from feeling so hopeless to so damned...  sadness
1   im grabbing a minute to post i feel greedy wrong    anger
2  i am ever feeling nostalgic about the fireplac...     love
3                               i am feeling grouchy    anger
4  ive been feeling a little burdened lately wasn...  sadness

In [6]:
test = pd.read_csv('test.csv')
test.columns =['Text','Emotion']

In [7]:
test.head()

Text  Emotion
0          im updating my blog because i feel shitty  sadness
1  i never make her separate from me because i do...  sadness
2  i left with my bouquet of red and yellow tulip...      joy
3    i was feeling a little vain when i did this one  sadness
4  i cant walk into a shop anywhere where i do no...     fear

In [9]:
# Create stopword list:
stopwords = set(STOPWORDS)
stopwords.update(["br", "href"])

In [10]:
def remove_punctuation(text):
    final = "".join(u for u in text if u not in ("?", ".", ";", ":",  "!",'"'))
    return final



In [13]:

df['Text'] = df['Text'].apply(remove_punctuation)

In [14]:
test['Text'] = test['Text'].apply(remove_punctuation)

In [15]:
X_train = df['Text']
y_train = df['Emotion']

In [16]:
X_test = test['Text']
y_test = test['Emotion']

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')
V_X_train = vectorizer.fit_transform(X_train)
V_X_test = vectorizer.transform(X_test)

In [18]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [19]:
lr.fit(V_X_train,y_train)

C:\Users\queenie.d.pamatian\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [22]:
predictions = lr.predict(V_X_test)


In [23]:
predictions

array(['sadness', 'sadness', 'joy', ..., 'joy', 'joy', 'fear'],
      dtype=object)

In [27]:
#key model metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
print("accuracy: ",accuracy_score(y_test, predictions))
print("confusion matrix: ",confusion_matrix(y_test, predictions))
#print("precision: ",precision_score(y_test,predictions))

accuracy:  0.8874437218609305
confusion matrix:  [[242   5   9   1  18   0]
 [  6 191   3   1  13  10]
 [  4   5 651  27   4   4]
 [  2   0  40 113   3   1]
 [ 14   7  15   3 539   2]
 [  2  13  11   0   2  38]]


In [45]:
from sklearn.ensemble import RandomForestClassifier 

classifier = RandomForestClassifier(n_estimators = 100, random_state = 0) 

# fit the model with x and y data 
forest = classifier.fit(V_X_train,y_train) 

y_pred = forest.predict(V_X_test)


In [46]:
#key model metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
print("accuracy: ",accuracy_score(y_test, y_pred))
print("confusion matrix: ",confusion_matrix(y_test, y_pred))
#print("precision: ",precision_score(y_test,predictions))

accuracy:  0.8679339669834918
confusion matrix:  [[233   8  22   1  10   1]
 [  9 184   7   0  13  11]
 [  3   5 652  19   7   9]
 [  2   0  53 101   2   1]
 [ 11   7  32   2 526   2]
 [  1  14  12   0   0  39]]


In [28]:
narrative = vectorizer.inverse_transform(V_X_test)

In [29]:
results = pd.DataFrame()
results['Text'] = narrative
results['Emotion'] = predictions

In [30]:
results.tail(100)

Text  Emotion
1899  [am, and, be, discouraged, feel, frustrated, i...  sadness
1900  [a, about, and, did, feel, i, little, nothing,...  sadness
1901  [about, ever, feel, i, it, music, passionate, ...     love
1902  [a, because, blank, feel, from, have, i, im, l...  sadness
1903  [a, acceptable, an, and, feel, i, is, not, sig...      joy
...                                                 ...      ...
1994  [all, and, are, at, back, being, can, close, d...    anger
1995  [a, after, appointment, cranky, doctors, feeli...    anger
1996  [a, achievement, am, and, feel, feeling, gives...      joy
1997  [as, can, comfortable, derby, feel, feeling, i...      joy
1998  [all, but, dont, face, feel, have, i, like, me...     fear

[100 rows x 2 columns]

In [60]:
from sklearn import svm
clf = svm.SVC()
svc = clf.fit(V_X_train,y_train)
svc_y = clf.predict(V_X_test)

In [84]:
new = ['She was mad upon hearing the shocking news']
new = vectorizer.transform(new)
print(svc.predict(new))
print(lr.predict(new))
print(classifier.predict(new))

['anger']
['anger']
['anger']
